apiVersion: v1
kind: Secret
metadata:
  name: {{ include "micro-auth-request.fullname" . }}
  labels:
    {{- include "micro-auth-request.labels" . | nindent 4 }}
type: Opaque
data:
  google_client_id: {{ .Values.google.client_id }}
  google_client_secret: {{ .Values.google.client_secret }}